name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      numOctocats:
        description: 'Number of Octocats'
        required: false
        default: '1'
      octocatEyeColor:
        description: 'Eye color of the Octocats'
        required: true
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
